### PR TITLE
File -> IO

### PR DESCRIPTION
**Pull request by edgarcosta**
The intrinsic File is undefined.

I have also replaced the single doublequote in intrinsics with a space, and created a .gitignore to ignore the .sig files.

### CODE REVIEW

**Comment by cjdoris** [comment]
Hi, thanks! The .gitignore and File -> IO makes sense.

But I don't understand why you've changed the docstrings from `{"}` to `{ }`? Unless the Magma syntax has changed, `{"}` means to copy the docstring from the intrinsic before.

**Comment by edgarcosta** [comment]
I'm sorry, I wasn't aware of that (horrible!) syntax. I will undo those
changes.

At some point while trying to fix
ListSignatures, which has been broken for a while due to magma, I wrongly
believed that those were the next culprit.

**Comment by cjdoris** [comment]
Thanks.

I've had issues with ListSignatures before but I can't totally remember what cased it. I think it was something to do with attaching/importing getting out of sync so when it goes to look up the signatures of some intrinsic then the intrinsic isn't actually there.

Is the issue caused by the code in this repo? i.e. does it not happen if you don't attach this repo?

**Comment by edgarcosta** [comment]
The only issue coming from this repo is that File should be IO.

ListSignatures previous to last magma version was broken due to magma's
package code referencing some non-existent code.
Now that they have fixed the issue I am trying to make sure that when one
loads the CHIMP package, which your package is part of, ListSignatures
keeps working :)

Once I'm back on a computer I will fix the PR.

Yup, it must have been some out of sync issue, that mislead me :)

**Comment by edgarcosta** [comment]
Fixed :)

**Comment by edgarcosta** [comment]
Also, let me know if you are open to adding more utils, and if so, do you have an automatic way to generate the docs?

**Comment by cjdoris** [comment]
Thanks!

**Comment by cjdoris** [comment]
Feel free to make PRs with extra functions.

The documentation is generated with this: https://github.com/cjdoris/magdoc

**Comment by edgarcosta** [comment]
tks! FYI, you closed the PR and didn't merge it

**Comment by cjdoris** [comment]
Ha, oops, thanks.

**Pull request merged**
